import type { Metadata } from "next";
import "./globals.css";
import TanStackProvider from "@/providers/tanstackQueryProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-Sen">
        <TanStackProvider>
          <main>{children}</main>
        </TanStackProvider>
        <Toaster />
      </body>
    </html>
  );
}
